#define TCC_VERSION "0.9.27"
#define CONFIG_TCC_STATIC 1
#define CONFIG_TCC_ELFINTERP "/XXX"
#define CONFIG_TCC_CRT_PREFIX "/XXX"
#define CONFIG_SYSROOT "/XXX"
#define inline
#define TCC_TARGET_X86_64 1
#define ONE_SOURCE 1
